### ISSUE TITLE
Radio Buttons not aligned

### ISSUE THREAD

**Issue by Xatenev** [delboy1978uk/form#2]
Take a look at the following screen:

https://raw.githubusercontent.com/delboy1978uk/form/master/tests/_data/dynamic-form.PNG

If you look closely you can see that the radio buttons are not aligned.

Please fix this ASAP. We cannot continue work otherwise

**Comment by delboy1978uk** [comment]
Our lives are ruined, all our profit - GONE!
Ok I'll look into it soon :-P

**Comment by shulcsm** [comment]
:+1:

**Comment by delboy1978uk** [comment]
Closing as a non issue. It's the CSS from that site! :-P
Compare https://cdn.pbrd.co/images/GT9sUo6.png
With https://pasteboard.co/GT9tZOx.png
